{
 "title": "Solana Validator",
 "description": "This dashboard can help you run a Solana validator. All metrics are fetched from RPC using the solana-monitor script. Please check our github https://github.com/htwtech/solana-monitoring . You are free to change this dashboard as you wish. ",
 "tags": [
  "Validator",
  "Solana"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } },
   {
    "name": "instance",
    "label": "Server",
    "query": {
     "query": "label_values({job=\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "<div style=\"display: flex; align-items: flex-start; gap: 12px;\">\r\n  <img \r\n    src=\"https://brand-kit.htw.tech/logo/logo_solana_style_64x64.png\"\r\n    style=\"height: 60px; width: auto; align-self: flex-start; margin-top: 0px;\">\r\n\r\n  <div style=\"flex: 1;\">\r\n    <div>\r\n      <b>Independence is in the code. Strength is in the consensus. Reliability is in our nodes.</b>\r\n      <p style=\"margin: 2px 0;\">\r\n        This dashboard can help you run a Solana validator. All metrics are fetched from RPC using the solana-monitor script. Please check our <a href=\"https://github.com/htwtech/solana-monitoring\" target=\"_blank\">GitHub\r\n        </a>. You are free to change this dashboard as you wish.\r\n      </p>\r\n    </div>\r\n    <div style=\"text-align: right;\">\r\n      Best regards, <a href=\"https://htw.tech/\" target=\"_blank\">Hightower team</a>.\r\n    </div>\r\n  </div>\r\n</div>\r\n\r\n"
   }
  },
  { "title": "Quick stats $name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "server" },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"${instance}\",job=\"${job}\"} - node_boot_time_seconds{instance=\"${instance}\",job=\"${job}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_validator_status{instance=\"${instance}\",job=\"${job}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Stake",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "SOL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_validator_activatedStake{instance=\"${instance}\",job=\"${job}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Leaderslots this epoch",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_validator_leaderSlots{instance=\"${instance}\",job=\"${job}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Missed Slots",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_validator_skippedSlots{instance=\"${instance}\",job=\"${job}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Skiprate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_validator_pctSkipped{instance=\"${instance}\",job=\"${job}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vote Percentage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_validator_epochCredits{instance=\"${instance}\" ,job=\"${job}\"} / (solana_validator_slotIndex{instance=\"${instance}\" ,job=\"${job}\"} * 16)  * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Credits Current Epoch",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_validator_epochCredits{instance=\"${instance}\" ,job=\"${job}\"}",
     "legendFormat": "Credits {{instance}}"
    }
   ]
  },
  {
   "title": "Credits Rate [5min]",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(solana_validator_credits{instance=\"${instance}\" ,job=\"${job}\"}[5m])",
     "legendFormat": "Credits {{instance}}"
    }
   ]
  },
  {
   "title": "Last Vote",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_validator_lastVote{instance=\"${instance}\",job=\"${job}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Root Slot",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_validator_rootSlot{instance=\"${instance}\",job=\"${job}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator Fee",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_validator_commission{instance=\"${instance}\",job=\"${job}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sys Load",
   "type": "stat",
   "description": "System load over all CPU cores together",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(node_load1{instance=\"$instance\",job=\"${job}\"}) * 100 / count(count(node_cpu_seconds_total{instance=\"$instance\",job=\"${job}\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Load 1m",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(node_load1{instance=\"${instance}\",job=\"${job}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"${instance}\",job=\"${job}\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"$instance\",job=\"${job}\"} / node_memory_MemTotal_bytes{instance=\"$instance\",job=\"${job}\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"${instance}\",job=\"${job}\"} - node_memory_SwapFree_bytes{instance=\"${instance}\",job=\"${job}\"}) / (node_memory_SwapTotal_bytes{instance=\"${instance}\",job=\"${job}\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IOWait",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_pressure_io_waiting_seconds_total{instance=\"${instance}\",job=\"${job}\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accounts usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"${instance}\" ,job=\"${job}\",  mountpoint=\"${accounts}\"} * 100) / node_filesystem_size_bytes{instance=\"${instance}\" ,job=\"${job}\",  mountpoint=\"${accounts}\"})"
    }
   ]
  },
  {
   "title": "Ledger usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"${instance}\" ,job=\"${job}\",  mountpoint=\"${ledger}\"} * 100) / node_filesystem_size_bytes{instance=\"${instance}\" ,job=\"${job}\",  mountpoint=\"${ledger}\"})"
    }
   ]
  },
  {
   "title": "/ usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"${instance}\"  ,job=\"${job}\", mountpoint=\"/\"} * 100) / node_filesystem_size_bytes{instance=\"${instance}\" ,job=\"${job}\",mountpoint=\"/\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_validator_epoch{instance=\"${instance}\",job=\"${job}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Epoch Ends",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_validator_epochEnds{instance=\"${instance}\" ,job=\"${job}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Epoch% Progress",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_validator_pctEpochElapsed{instance=\"${instance}\" ,job=\"${job}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Solana TPS [5min]",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(solana_validator_tps{instance=\"$instance\",job=\"${job}\"}[5m])",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "Solana Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_validator_version{instance=\"${instance}\",job=\"${job}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last update",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_validator_timeStamp{instance=\"${instance}\",job=\"${job}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Validator Stats $name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Vote Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "solana_validator_epochCredits{instance=\"${instance}\" ,job=\"${job}\"} / (solana_validator_slotIndex{instance=\"${instance}\" ,job=\"${job}\"} * 16)  * 100",
     "legendFormat": "Vote Percentage"
    }
   ]
  },
  {
   "title": "Root Distance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Slot" } },
   "targets": [
    {
     "expr": "solana_validator_rootDistance{instance=\"${instance}\" ,job=\"${job}\"}"
    }
   ]
  },
  {
   "title": "Credits Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "solana_validator_epochCredits{instance=\"${instance}\" ,job=\"${job}\"} - solana_validator_slotIndex{instance=\"${instance}\" ,job=\"${job}\"} * 16 ",
     "legendFormat": "Credits lag"
    }
   ]
  },
  {
   "title": "Vote Distance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "solana_validator_voteDistance{instance=\"${instance}\" ,job=\"${job}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Credits Rate [5min]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "delta(solana_validator_credits{instance=\"${instance}\" ,job=\"${job}\"}[5m])",
     "legendFormat": "Credits {{instance}}"
    }
   ]
  },
  {
   "title": "My Leaderslots",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "solana_validator_leaderSlots{instance=\"${instance}\" ,job=\"${job}\"}",
     "legendFormat": "Leaderslots"
    },
    {
     "expr": "solana_validator_skippedSlots{instance=\"${instance}\" ,job=\"${job}\"}",
     "legendFormat": "Skipped"
    }
   ]
  },
  {
   "title": "Credits Current Epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "solana_validator_epochCredits{instance=\"${instance}\" ,job=\"${job}\"}",
     "legendFormat": "Current Credits"
    },
    {
     "expr": "solana_validator_slotIndex{instance=\"${instance}\" ,job=\"${job}\"} * 16",
     "legendFormat": "Max Possible Credits"
    }
   ]
  },
  {
   "title": "Balance on Identity Acccount [SOL]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "SOL" } },
   "targets": [
    {
     "expr": "solana_validator_validatorBalance{instance=\"${instance}\" ,job=\"${job}\"}",
     "legendFormat": "Balance"
    }
   ]
  },
  {
   "title": "Skiprate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "solana_validator_pctSkipped{instance=\"${instance}\" ,job=\"${job}\"}",
     "legendFormat": "My Skiprate"
    },
    {
     "expr": "solana_validator_pctTotSkipped{instance=\"${instance}\" ,job=\"${job}\"}",
     "legendFormat": "Cluster Skiprate"
    }
   ]
  },
  {
   "title": "Active Stake [SOL]",
   "type": "timeseries",
   "description": "Active stake on the validator.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "SOL" } },
   "targets": [
    {
     "expr": "solana_validator_activatedStake{instance=\"${instance}\" ,job=\"${job}\"}",
     "legendFormat": "Stake"
    }
   ]
  },
  {
   "title": "% Cluster Total Delinquent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "solana_validator_pctTotDelinquent{instance=\"${instance}\" ,job=\"${job}\"}",
     "legendFormat": "% Total Delinquent"
    }
   ]
  },
  {
   "title": "Balance on Vote Account [SOL]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "solana_validator_validatorVoteBalance{instance=\"${instance}\" ,job=\"${job}\"}",
     "legendFormat": "Balance"
    }
   ]
  },
  {
   "title": "Solana TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "rate(solana_validator_tps{instance=\"$instance\" ,job=\"${job}\"}[5m])",
     "legendFormat": "TPS"
    }
   ]
  },
  { "title": "System Stats $name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$instance\", mode=\"system\" ,job=\"${job}\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$instance\" ,job=\"${job}\"}) by (cpu)))",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$instance\", mode=\"user\" ,job=\"${job}\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$instance\" ,job=\"${job}\"}) by (cpu)))",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$instance\", mode=\"nice\" ,job=\"${job}\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$instance\" ,job=\"${job}\"}) by (cpu)))",
     "legendFormat": "Nice - Niced processes executing in user mode"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$instance\", mode=\"iowait\" ,job=\"${job}\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$instance\" ,job=\"${job}\"}) by (cpu)))",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$instance\", mode=\"irq\" ,job=\"${job}\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$instance\" ,job=\"${job}\"}) by (cpu)))",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$instance\", mode=\"softirq\" ,job=\"${job}\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$instance\" ,job=\"${job}\"}) by (cpu)))",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$instance\", mode=\"steal\" ,job=\"${job}\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$instance\" ,job=\"${job}\"}) by (cpu)))",
     "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$instance\", mode=\"idle\" ,job=\"${job}\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$instance\" ,job=\"${job}\"}) by (cpu)))",
     "legendFormat": "Idle - Waiting for something to happen"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$instance\",device!~'rootfs' ,job=\"${job}\"} * 100) / node_filesystem_size_bytes{instance=\"$instance\",device!~'rootfs' ,job=\"${job}\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\" ,job=\"${job}\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\" ,job=\"${job}\"} - node_memory_MemFree_bytes{instance=\"$instance\" ,job=\"${job}\"} - (node_memory_Cached_bytes{instance=\"$instance\" ,job=\"${job}\"} + node_memory_Buffers_bytes{instance=\"$instance\" ,job=\"${job}\"} + node_memory_SReclaimable_bytes{instance=\"$instance\" ,job=\"${job}\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$instance\" ,job=\"${job}\"} + node_memory_Buffers_bytes{instance=\"$instance\" ,job=\"${job}\"} + node_memory_SReclaimable_bytes{instance=\"$instance\" ,job=\"${job}\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$instance\" ,job=\"${job}\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$instance\" ,job=\"${job}\"} - node_memory_SwapFree_bytes{instance=\"$instance\" ,job=\"${job}\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Disk IOps Completed",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=\"$instance\" ,job=\"${job}\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=\"$instance\" ,job=\"${job}\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Writes completed"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "solana_validator_openFiles{instance=\"${instance}\" ,job=\"${job}\"}",
     "legendFormat": "Open Files"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=\"$instance\" ,job=\"${job}\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=\"$instance\" ,job=\"${job}\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Written bytes"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"$instance\" ,job=\"${job}\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"$instance\" ,job=\"${job}\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Network Errors [1m]",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "delta(node_network_receive_errs_total{instance=\"$instance\" ,job=\"${job}\"}[1m])",
     "legendFormat": "{{device}} - Receive errors"
    },
    {
     "expr": "delta(node_network_transmit_errs_total{instance=\"$instance\" ,job=\"${job}\"}[1m])",
     "legendFormat": "{{device}} - Transmit errors"
    }
   ]
  }
 ]
}